# Generated by Django 4.0.1 on 2022-02-27 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_topic_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comment',
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='本文'),
            preserve_default=False,
        ),
    ]
